language: java
jdk:
  - oraclejdk8
install:
  - npm install -g gulp
  - npm install --save-dev gulp
  - npm install --global gulp-cli bower
sudo: false
cache:
  directories:
  - $HOME/.m2
  - node_modules
